<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cssao.Application\Cssao.Application.csproj" />
    <ProjectReference Include="..\Cssao.Domain\Cssao.Domain.csproj" />
    <ProjectReference Include="..\Cssao.Shared\Cssao.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.4" />-->
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
  </ItemGroup>
</Project>
