<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\INewsService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cssao.Domain\Cssao.Domain.csproj" />
    <ProjectReference Include="..\Cssao.Shared\Cssao.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="FluentValidation" Version="11.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>
</Project>
